source 'https://rubygems.org'

gem 'rails', '3.2.9'

gem 'json', '~> 1.7.5'
gem 'simple_form', '~> 2.0.4'
# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3', '~> 1.3.6',  :groups => [:test, :development]
#gem 'pg', '~> 0.14.1',      :groups => :production
#gem 'geocoder'
gem 'omniauth-twitter'
# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'twitter-bootstrap-rails', '~> 2.1.4'
  gem 'jquery-ui-rails', '~> 2.0.2'
  gem 'jquery-datatables-rails', '~> 1.11.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :development, :test do
  gem 'hirb', '~> 0.7.0'
  gem 'quiet_assets', '~> 1.0.1'  # wylacza logowanie *assets pipeline*
  gem 'rspec-rails', '~> 2.11.0'
end

gem 'less-rails', '~> 2.2.6'
gem 'therubyracer', '~> 0.10.2'

gem 'thin'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
